import { getSpecsCollection } from '$lib/server/db';
import { ObjectId } from 'mongodb';
import { error } from '@sveltejs/kit';

export const GET = async ({ params }) => {
    const specsColl = await getSpecsCollection();
    let spec;

    try {
        spec = await specsColl.findOne({ _id: new ObjectId(params.id) });
    } catch (e) {
        throw error(404, 'Spec not found');
    }

    if (!spec) throw error(404, 'Spec not found');

    const markdown = `# Feature Spec: ${spec.goal}

## Goal
${spec.goal}

## Target Users
${spec.users}

## Constraints
${spec.constraints || 'None'}

## User Stories
${spec.userStories.map(s => `- ${s}`).join('\n')}

## Engineering Tasks
### Frontend
${spec.tasks.filter(t => t.group === 'frontend').map(t => `- [ ] ${t.title}`).join('\n')}

### Backend
${spec.tasks.filter(t => t.group === 'backend').map(t => `- [ ] ${t.title}`).join('\n')}

### Testing
${spec.tasks.filter(t => t.group === 'testing').map(t => `- [ ] ${t.title}`).join('\n')}

## Risks / Unknowns
${spec.risks.map(r => `- ${r}`).join('\n')}

Generated by AI Tasks Generator
`;

    return new Response(markdown, {
        headers: {
            'Content-Type': 'text/markdown',
            'Content-Disposition': `attachment; filename="spec-${params.id}.md"`
        }
    });
};
